# Generated by Django 3.1.1 on 2023-04-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('offers', models.BooleanField(default=False)),
            ],
        ),
    ]
